services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    env_file:
      - ../.env
    network_mode: host
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
